#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${SKILLSET_INSTALL_E2E_IMAGE:-skillset-install-e2e:local}"
INSTALL_URL="${SKILLSET_INSTALL_URL:-https://skillset.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
SKILLSET_E2E_MODELS="${SKILLSET_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker run --rm \
  -e SKILLSET_INSTALL_URL="$INSTALL_URL" \
  -e SKILLSET_INSTALL_TAG="${SKILLSET_INSTALL_TAG:-latest}" \
  -e SKILLSET_E2E_MODELS="$SKILLSET_E2E_MODELS" \
  -e SKILLSET_INSTALL_E2E_PREVIOUS="${SKILLSET_INSTALL_E2E_PREVIOUS:-}" \
  -e SKILLSET_INSTALL_E2E_SKIP_PREVIOUS="${SKILLSET_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e SKILLSET_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS="${SKILLSET_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS:-600}" \
  -e SKILLSET_NO_ONBOARD=1 \
  -e OPENAI_API_KEY \
  -e ANTHROPIC_API_KEY \
  -e ANTHROPIC_API_TOKEN \
  "$IMAGE_NAME"
