export const browserCoreExamples = [
  "skillset browser status",
  "skillset browser start",
  "skillset browser stop",
  "skillset browser tabs",
  "skillset browser open https://example.com",
  "skillset browser focus abcd1234",
  "skillset browser close abcd1234",
  "skillset browser screenshot",
  "skillset browser screenshot --full-page",
  "skillset browser screenshot --ref 12",
  "skillset browser snapshot",
  "skillset browser snapshot --format aria --limit 200",
  "skillset browser snapshot --efficient",
  "skillset browser snapshot --labels",
];

export const browserActionExamples = [
  "skillset browser navigate https://example.com",
  "skillset browser resize 1280 720",
  "skillset browser click 12 --double",
  'skillset browser type 23 "hello" --submit',
  "skillset browser press Enter",
  "skillset browser hover 44",
  "skillset browser drag 10 11",
  "skillset browser select 9 OptionA OptionB",
  "skillset browser upload /tmp/skillset/uploads/file.pdf",
  'skillset browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "skillset browser dialog --accept",
  'skillset browser wait --text "Done"',
  "skillset browser evaluate --fn '(el) => el.textContent' --ref 7",
  "skillset browser console --level error",
  "skillset browser pdf",
];
